/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.supermarketmanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

public class BillingForm extends javax.swing.JFrame {
    
    private ArrayList<Product> products;

    public BillingForm() {
        initComponents();
        products = Product.fetchProducts();
        displayProducts();
        GetCat();
    }
    private void displayProducts() {
        String[] columnNames = {"Name", "Quantity", "Price", "Category"};
        String[][] data = new String[products.size()][];
        for (int i = 0; i < products.size(); i++) {
            Product product = products.get(i);
            data[i] = new String[] {
                product.getName(), String.valueOf(product.getQuantity()),
                String.valueOf(product.getPrice()), product.getCategory()
            };
        }
        
        ProductTable.setModel(new DefaultTableModel(data, columnNames));
    }
    
    private void GetCat(){
        ArrayList<String> categories = Product.fetchCategories();
        for (String category: categories) {
            CatCb.addItem(category);
        }
        
    }
    int PrI,newQty;
    public void Update(){
            try{
                Connection Con = Database.getInstance().getConnection();
            Statement St = Con.createStatement();
            String query ="Update PRODUCTTBL set PRODQTY="+newQty+""+"where PRODID="+PrI;
               St.executeUpdate(query);
                products = Product.fetchProducts();
                displayProducts();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        prodName_field = new javax.swing.JTextField();
        billingPoint = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        prodQty_field = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CatCb = new javax.swing.JComboBox<>();
        addTobill_btn = new javax.swing.JButton();
        total_btn = new javax.swing.JButton();
        refresh_btn = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductTable = new javax.swing.JTable();
        productsList = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bill_txtArea = new javax.swing.JTextArea();
        filter_btn = new javax.swing.JButton();
        byName_btn = new javax.swing.JButton();
        close_label = new javax.swing.JLabel();
        logout_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(249, 125, 42));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        prodName_field.setEditable(false);
        prodName_field.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        prodName_field.setForeground(new java.awt.Color(249, 125, 42));
        prodName_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodName_fieldActionPerformed(evt);
            }
        });

        billingPoint.setBackground(new java.awt.Color(255, 255, 255));
        billingPoint.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        billingPoint.setForeground(new java.awt.Color(249, 125, 42));
        billingPoint.setText("BILLING POINT");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(249, 125, 42));
        jLabel5.setText("NAME");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(249, 125, 42));

        prodQty_field.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        prodQty_field.setForeground(new java.awt.Color(249, 125, 42));
        prodQty_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodQty_fieldActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(249, 125, 42));
        jLabel7.setText("QUANTITY");

        CatCb.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CatCb.setForeground(new java.awt.Color(249, 125, 42));
        CatCb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CatCbMouseClicked(evt);
            }
        });
        CatCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatCbActionPerformed(evt);
            }
        });

        addTobill_btn.setBackground(new java.awt.Color(249, 125, 42));
        addTobill_btn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        addTobill_btn.setForeground(new java.awt.Color(255, 255, 255));
        addTobill_btn.setText("Add to bill");
        addTobill_btn.setBorderPainted(false);
        addTobill_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addTobill_btnMouseClicked(evt);
            }
        });
        addTobill_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTobill_btnActionPerformed(evt);
            }
        });

        total_btn.setBackground(new java.awt.Color(249, 125, 42));
        total_btn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        total_btn.setForeground(new java.awt.Color(255, 255, 255));
        total_btn.setText("Total");
        total_btn.setBorderPainted(false);
        total_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                total_btnMouseClicked(evt);
            }
        });
        total_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_btnActionPerformed(evt);
            }
        });

        refresh_btn.setBackground(new java.awt.Color(249, 125, 42));
        refresh_btn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        refresh_btn.setForeground(new java.awt.Color(255, 255, 255));
        refresh_btn.setText("Refresh");
        refresh_btn.setBorderPainted(false);
        refresh_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refresh_btnMouseClicked(evt);
            }
        });
        refresh_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_btnActionPerformed(evt);
            }
        });

        clear_btn.setBackground(new java.awt.Color(249, 125, 42));
        clear_btn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        clear_btn.setForeground(new java.awt.Color(255, 255, 255));
        clear_btn.setText("Clear");
        clear_btn.setBorderPainted(false);
        clear_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clear_btnMouseClicked(evt);
            }
        });
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });

        ProductTable.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        ProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "QUANTITY", "PRICE", "CATEGORY"
            }
        ));
        ProductTable.setRowHeight(25);
        ProductTable.setSelectionBackground(new java.awt.Color(249, 125, 42));
        ProductTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        ProductTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ProductTable);

        productsList.setBackground(new java.awt.Color(255, 255, 255));
        productsList.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        productsList.setForeground(new java.awt.Color(249, 125, 42));
        productsList.setText("PRODUCTS LIST");

        bill_txtArea.setEditable(false);
        bill_txtArea.setColumns(20);
        bill_txtArea.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bill_txtArea.setRows(5);
        bill_txtArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bill_txtAreaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(bill_txtArea);

        filter_btn.setBackground(new java.awt.Color(249, 125, 42));
        filter_btn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        filter_btn.setForeground(new java.awt.Color(255, 255, 255));
        filter_btn.setText("Filter");
        filter_btn.setBorderPainted(false);
        filter_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filter_btnMouseClicked(evt);
            }
        });
        filter_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filter_btnActionPerformed(evt);
            }
        });

        byName_btn.setBackground(new java.awt.Color(249, 125, 42));
        byName_btn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        byName_btn.setForeground(new java.awt.Color(255, 255, 255));
        byName_btn.setText("Search By Name");
        byName_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                byName_btnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(prodQty_field, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(prodName_field, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(addTobill_btn)
                                .addGap(72, 72, 72)
                                .addComponent(clear_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(byName_btn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(productsList)
                        .addGap(149, 149, 149))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(CatCb, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(filter_btn)
                        .addGap(18, 18, 18)
                        .addComponent(refresh_btn)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(15, 15, 15))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(billingPoint)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(total_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(billingPoint)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prodName_field, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prodQty_field, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addTobill_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clear_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(267, 267, 267))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(productsList)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(refresh_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(filter_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CatCb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(byName_btn))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(total_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );

        close_label.setBackground(new java.awt.Color(255, 255, 255));
        close_label.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        close_label.setForeground(new java.awt.Color(255, 255, 255));
        close_label.setText("X");
        close_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_labelMouseClicked(evt);
            }
        });

        logout_label.setBackground(new java.awt.Color(255, 255, 255));
        logout_label.setFont(new java.awt.Font("Century Gothic", 2, 20)); // NOI18N
        logout_label.setForeground(new java.awt.Color(255, 255, 255));
        logout_label.setText("LOGOUT");
        logout_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_labelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(close_label)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(logout_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(logout_label))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(close_label)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(71, 71, 71))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 32, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void prodName_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodName_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodName_fieldActionPerformed

    private void prodQty_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodQty_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodQty_fieldActionPerformed

    private void CatCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CatCbActionPerformed
    int i=0;
    private void addTobill_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTobill_btnMouseClicked
        try{
            newQty = AvailQty - Integer.parseInt(prodQty_field.getText().trim());
        ProdTot = Uprice * Integer.valueOf(prodQty_field.getText().trim());
        if(prodQty_field.getText().isEmpty()||prodName_field.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Missing Information!");
        }
        else if (AvailQty <= Integer.parseInt(prodQty_field.getText()))
            JOptionPane.showMessageDialog(this,"Not Enough in Stock!");
        else{
            i++;
            ProdTot = Uprice * Double.valueOf(prodQty_field.getText());
            GrdTotal = GrdTotal+ProdTot;
            if(i==1){
                bill_txtArea.setText(bill_txtArea.getText()+"         ==============FUVSSSS MART==============\n" +" NUM     PRODUCT     PRICE     QUANTITY     TOTAL\n"+" "+i+"            "+prodName_field.getText()+"         "+Uprice+"            "+prodQty_field.getText()+"        "+ProdTot+"\n");
            }
            else{
                bill_txtArea.setText(bill_txtArea.getText()+" "+i+"            "+prodName_field.getText()+"         "+Uprice+"            "+prodQty_field.getText()+"        "+ProdTot+"\n");
            }
            Update();
        }}
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Wrong Input");}
    }//GEN-LAST:event_addTobill_btnMouseClicked

    private void addTobill_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTobill_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTobill_btnActionPerformed

    private void total_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_total_btnMouseClicked
    String msg = "MEMBERSHIP?";
    int ans = JOptionPane.showConfirmDialog(this, msg);
    if(ans==JOptionPane.YES_OPTION){
        new MemberCheck(GrdTotal).setVisible(true);
    }
    else if(ans==JOptionPane.NO_OPTION){
        JOptionPane.showMessageDialog(this, "Total Bill is: RS."+GrdTotal);
    }
    }//GEN-LAST:event_total_btnMouseClicked
    
    private void total_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_btnActionPerformed

    private void refresh_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refresh_btnMouseClicked
//      SelectProduct();
        products = Product.fetchProducts();
        displayProducts();
    }//GEN-LAST:event_refresh_btnMouseClicked

    private void refresh_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refresh_btnActionPerformed

    private void clear_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clear_btnMouseClicked

        prodName_field.setText("");
        prodQty_field.setText("");
    }//GEN-LAST:event_clear_btnMouseClicked

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clear_btnActionPerformed
    Double Uprice,ProdTot=0.0;
    double GrdTotal=0.0;
    int AvailQty;
    private void ProductTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductTableMouseClicked
        DefaultTableModel model = (DefaultTableModel) ProductTable.getModel();
        int Myindex = ProductTable.getSelectedRow();
        PrI = products.get(Myindex).getId();
        Uprice = products.get(Myindex).getPrice();
        AvailQty = products.get(Myindex).getQuantity();
        prodName_field.setText(products.get(Myindex).getName());
        
    }//GEN-LAST:event_ProductTableMouseClicked

    private void close_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_labelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_close_labelMouseClicked

    private void logout_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_labelMouseClicked
        new LoginForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logout_labelMouseClicked

    private void CatCbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CatCbMouseClicked
        
    }//GEN-LAST:event_CatCbMouseClicked

    private void filter_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filter_btnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_filter_btnMouseClicked

    private void filter_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filter_btnActionPerformed
        products = Product.fetchProductsbyCat(CatCb.getSelectedItem().toString());
        displayProducts();
    }//GEN-LAST:event_filter_btnActionPerformed

    private void bill_txtAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bill_txtAreaMouseClicked
        bill_txtArea.setText("");
        i = 0;
    }//GEN-LAST:event_bill_txtAreaMouseClicked

    private void byName_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_byName_btnMouseClicked
        String name = JOptionPane.showInputDialog("Enter Name Of The Product: ");
        products = Product.fetchByName(name);
        displayProducts();
    }//GEN-LAST:event_byName_btnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillingForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CatCb;
    private javax.swing.JTable ProductTable;
    private javax.swing.JButton addTobill_btn;
    private javax.swing.JTextArea bill_txtArea;
    private javax.swing.JLabel billingPoint;
    private javax.swing.JButton byName_btn;
    private javax.swing.JButton clear_btn;
    private javax.swing.JLabel close_label;
    private javax.swing.JButton filter_btn;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel logout_label;
    private javax.swing.JTextField prodName_field;
    private javax.swing.JTextField prodQty_field;
    private javax.swing.JLabel productsList;
    private javax.swing.JButton refresh_btn;
    private javax.swing.JButton total_btn;
    // End of variables declaration//GEN-END:variables
}
