/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.supermarketmanagement;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.derby.shared.common.error.DerbySQLIntegrityConstraintViolationException;

/**
 *
 * @author HP
 */
public class CustomerForm extends javax.swing.JFrame {
    private ArrayList<Customer> cus;
    public CustomerForm() {
        initComponents();
        cus = Customer.fetchCustomer();
        displayCust();
    }
    
    public void displayCust(){
        String [] columnNames = {"ID","Name","Gender","Number","Address","Valid Till","Status"};
        String data[][] = new String[cus.size()][];
        for(int i=0;i<cus.size();i++){
            Customer c = cus.get(i);
            data[i] = new String []{String.valueOf(c.getId()),c.getName(),c.getGender(),c.getPhoneNumber(),c.getAddress(),c.getValidTill().toString(),c.getMemberStatus()};
        }
        CusTable.setModel(new DefaultTableModel(data,columnNames));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        manageCat = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cusId_field = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cusName_field = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cusPhone_field = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        GenderCb = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cusAddress_field = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cusValid_field = new javax.swing.JTextField();
        add_btn = new javax.swing.JButton();
        edit_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CusTable = new javax.swing.JTable();
        CusStatusCb = new javax.swing.JComboBox<>();
        byName_btn = new javax.swing.JButton();
        refresh_btn = new javax.swing.JButton();
        close_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        manageCat.setBackground(new java.awt.Color(255, 255, 255));
        manageCat.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        manageCat.setForeground(new java.awt.Color(249, 125, 42));
        manageCat.setText("MANAGE MEMBERSHIPS");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(249, 125, 42));
        jLabel3.setText("CUSTOMER ID");

        cusId_field.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cusId_field.setForeground(new java.awt.Color(249, 125, 42));
        cusId_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusId_fieldActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(249, 125, 42));
        jLabel5.setText("NAME");

        cusName_field.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cusName_field.setForeground(new java.awt.Color(249, 125, 42));
        cusName_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusName_fieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(249, 125, 42));
        jLabel2.setText("PHONE#");

        cusPhone_field.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cusPhone_field.setForeground(new java.awt.Color(249, 125, 42));
        cusPhone_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusPhone_fieldActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(249, 125, 42));
        jLabel8.setText("GENDER");

        GenderCb.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        GenderCb.setForeground(new java.awt.Color(249, 125, 42));
        GenderCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        GenderCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderCbActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(249, 125, 42));
        jLabel6.setText("ADDRESS");

        cusAddress_field.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cusAddress_field.setForeground(new java.awt.Color(249, 125, 42));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(249, 125, 42));
        jLabel7.setText("MEMBERSHIP");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(249, 125, 42));
        jLabel9.setText("VALID TILL");

        cusValid_field.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cusValid_field.setForeground(new java.awt.Color(249, 125, 42));
        cusValid_field.setText("YY-MM-DD");
        cusValid_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cusValid_fieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cusValid_fieldFocusLost(evt);
            }
        });
        cusValid_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusValid_fieldActionPerformed(evt);
            }
        });

        add_btn.setBackground(new java.awt.Color(249, 125, 42));
        add_btn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        add_btn.setForeground(new java.awt.Color(255, 255, 255));
        add_btn.setText("Add");
        add_btn.setBorderPainted(false);
        add_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_btnMouseClicked(evt);
            }
        });
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        edit_btn.setBackground(new java.awt.Color(249, 125, 42));
        edit_btn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        edit_btn.setForeground(new java.awt.Color(255, 255, 255));
        edit_btn.setText("Edit");
        edit_btn.setBorderPainted(false);
        edit_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit_btnMouseClicked(evt);
            }
        });
        edit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_btnActionPerformed(evt);
            }
        });

        delete_btn.setBackground(new java.awt.Color(249, 125, 42));
        delete_btn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        delete_btn.setForeground(new java.awt.Color(255, 255, 255));
        delete_btn.setText("Delete");
        delete_btn.setBorderPainted(false);
        delete_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_btnMouseClicked(evt);
            }
        });
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        clear_btn.setBackground(new java.awt.Color(249, 125, 42));
        clear_btn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        clear_btn.setForeground(new java.awt.Color(255, 255, 255));
        clear_btn.setText("Clear");
        clear_btn.setBorderPainted(false);
        clear_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clear_btnMouseClicked(evt);
            }
        });
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });

        CusTable.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        CusTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        CusTable.setRowHeight(25);
        CusTable.setSelectionBackground(new java.awt.Color(249, 125, 42));
        CusTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        CusTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CusTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CusTable);

        CusStatusCb.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CusStatusCb.setForeground(new java.awt.Color(249, 125, 42));
        CusStatusCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ON", "OFF" }));
        CusStatusCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CusStatusCbActionPerformed(evt);
            }
        });

        byName_btn.setBackground(new java.awt.Color(249, 125, 42));
        byName_btn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        byName_btn.setForeground(new java.awt.Color(255, 255, 255));
        byName_btn.setText("Search By Name");
        byName_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                byName_btnMouseClicked(evt);
            }
        });

        refresh_btn.setBackground(new java.awt.Color(249, 125, 42));
        refresh_btn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        refresh_btn.setForeground(new java.awt.Color(255, 255, 255));
        refresh_btn.setText("Refresh");
        refresh_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refresh_btnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(353, 353, 353)
                .addComponent(manageCat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refresh_btn))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(byName_btn)
                        .addGap(52, 52, 52)
                        .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177)
                        .addComponent(delete_btn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(27, 27, 27)
                                        .addComponent(cusId_field, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel5))
                                        .addGap(63, 63, 63)
                                        .addComponent(cusPhone_field, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(180, 180, 180)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(GenderCb, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(cusName_field, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(edit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(98, 98, 98))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cusAddress_field, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(CusStatusCb, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(clear_btn)
                                                .addGap(69, 69, 69)))
                                        .addComponent(cusValid_field, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(44, 44, 44))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageCat)
                    .addComponent(refresh_btn))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cusId_field, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(GenderCb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cusName_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(cusAddress_field, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cusValid_field, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel2)
                    .addComponent(cusPhone_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CusStatusCb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_btn)
                    .addComponent(clear_btn)
                    .addComponent(byName_btn))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        close_label.setBackground(new java.awt.Color(255, 255, 255));
        close_label.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        close_label.setForeground(new java.awt.Color(255, 255, 255));
        close_label.setText("X");
        close_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_labelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(close_label)
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(close_label, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cusId_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusId_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusId_fieldActionPerformed

    private void cusName_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusName_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusName_fieldActionPerformed

    private void cusPhone_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusPhone_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusPhone_fieldActionPerformed

    private void GenderCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderCbActionPerformed

    private void add_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_btnMouseClicked
        Date date = Date.valueOf(cusValid_field.getText());
        if (cusId_field.getText().isEmpty() || cusName_field.getText().isEmpty() || cusPhone_field.getText().isEmpty() || cusAddress_field.getText().isEmpty()
                || cusValid_field.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Missing Information!");
        } else if (Customer.datePassed(date)) {
            JOptionPane.showMessageDialog(this, "Invalid Date!");
            cusValid_field.setText("");
        } else {
            try {
                Connection Con = Database.getInstance().getConnection();
                PreparedStatement add = Con.prepareStatement("insert into CUSTOMERSTBL values(?,?,?,?,?,?,?)");
                add.setInt(1, Integer.parseInt(cusId_field.getText()));
                add.setString(2,cusName_field.getText());
                add.setString(3, GenderCb.getSelectedItem().toString());
                add.setString(4,cusPhone_field.getText());
                add.setString(5,cusAddress_field.getText());
                add.setDate(6, date);
                add.setString(7, CusStatusCb.getSelectedItem().toString());
                add.executeUpdate();
                cus = Customer.fetchCustomer();
                displayCust();
            } 
            catch(DerbySQLIntegrityConstraintViolationException e){
            JOptionPane.showMessageDialog(this, "ID ALREADY EXISTS!");
            cusId_field.setText("");
        }catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, "Wrong Input");
        }catch (SQLException e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_add_btnMouseClicked

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_btnActionPerformed

    private void edit_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_btnMouseClicked
        Date date = Date.valueOf(cusValid_field.getText());
        if (cusId_field.getText().isEmpty() || cusName_field.getText().isEmpty() || cusPhone_field.getText().isEmpty() || cusAddress_field.getText().isEmpty()
                || cusValid_field.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Missing Information!");
        } else if (Customer.datePassed(date)) {
            JOptionPane.showMessageDialog(this, "Invalid Date!");
            cusValid_field.setText("");
        } else {
            try {
                Connection Con = Database.getInstance().getConnection();
                PreparedStatement add = Con.prepareStatement("UPDATE CUSTOMERSTBL SET CUSNAME=?, CUSGENDER=?, CUSNUMBER=?, CUSADDRESS=?, VALIDTILL=?, "
                        + "CUSSTATUS=? WHERE CUSID=?");
                add.setString(1, cusName_field.getText());
                add.setString(2, GenderCb.getSelectedItem().toString());
                add.setString(3, cusPhone_field.getText());
                add.setString(4, cusAddress_field.getText());
                add.setDate(5, date);
                add.setString(6, CusStatusCb.getSelectedItem().toString());
                add.setInt(7, Integer.parseInt(cusId_field.getText()));
                add.executeUpdate();
                cus = Customer.fetchCustomer();
                displayCust();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_edit_btnMouseClicked

    private void edit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_btnActionPerformed

    private void delete_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_btnMouseClicked
        if (cusId_field.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "Enter The Product ID To Be Deleted");
        else {
            try {
                Connection Con = Database.getInstance().getConnection();
                String query = "Delete from CUSTOMERSTBL where CUSID = " + cusId_field.getText();
                Statement St = Con.createStatement();
                St.executeUpdate(query);
                cus = Customer.fetchCustomer();
                displayCust();
                JOptionPane.showMessageDialog(this, "Product Deleted Successfully!");
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_delete_btnMouseClicked

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_btnActionPerformed

    private void clear_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clear_btnMouseClicked
        cusId_field.setText("");
        cusName_field.setText("");
        cusAddress_field.setText("");
        cusPhone_field.setText("");
        cusValid_field.setText("");
    }//GEN-LAST:event_clear_btnMouseClicked

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clear_btnActionPerformed

    private void CusTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CusTableMouseClicked
        DefaultTableModel model = (DefaultTableModel)CusTable.getModel();
        int myIndex = CusTable.getSelectedRow();
        cusId_field.setText(model.getValueAt(myIndex, 0).toString());
        cusName_field.setText(model.getValueAt(myIndex, 1).toString());
        GenderCb.setSelectedItem(model.getValueAt(myIndex, 2).toString());
        cusPhone_field.setText(model.getValueAt(myIndex, 3).toString());
        cusAddress_field.setText(model.getValueAt(myIndex, 4).toString());
        cusValid_field.setText(model.getValueAt(myIndex, 5).toString());
        CusStatusCb.setSelectedItem(model.getValueAt(myIndex, 6).toString());
    }//GEN-LAST:event_CusTableMouseClicked

    private void cusValid_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cusValid_fieldFocusGained
        if(cusValid_field.getText().equals("YY-MM-DD"))
            cusValid_field.setText("");
    }//GEN-LAST:event_cusValid_fieldFocusGained

    private void cusValid_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cusValid_fieldFocusLost
        if(cusValid_field.getText().equals(""))
            cusValid_field.setText("YY-MM-DD");
    }//GEN-LAST:event_cusValid_fieldFocusLost

    private void cusValid_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusValid_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusValid_fieldActionPerformed

    private void close_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_labelMouseClicked
        this.dispose();
    }//GEN-LAST:event_close_labelMouseClicked

    private void CusStatusCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CusStatusCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CusStatusCbActionPerformed

    private void byName_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_byName_btnMouseClicked
        String name = JOptionPane.showInputDialog("Enter Name Of The Member: ");
        cus = Customer.fetchByName(name);
        displayCust();
    }//GEN-LAST:event_byName_btnMouseClicked

    private void refresh_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refresh_btnMouseClicked
        cus=Customer.fetchCustomer();
        displayCust();
    }//GEN-LAST:event_refresh_btnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CusStatusCb;
    private javax.swing.JTable CusTable;
    private javax.swing.JComboBox<String> GenderCb;
    private javax.swing.JButton add_btn;
    private javax.swing.JButton byName_btn;
    private javax.swing.JButton clear_btn;
    private javax.swing.JLabel close_label;
    private javax.swing.JTextField cusAddress_field;
    private javax.swing.JTextField cusId_field;
    private javax.swing.JTextField cusName_field;
    private javax.swing.JTextField cusPhone_field;
    private javax.swing.JTextField cusValid_field;
    private javax.swing.JButton delete_btn;
    private javax.swing.JButton edit_btn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel manageCat;
    private javax.swing.JButton refresh_btn;
    // End of variables declaration//GEN-END:variables
}
