/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.supermarketmanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLSyntaxErrorException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import org.apache.derby.shared.common.error.DerbySQLIntegrityConstraintViolationException;

/**
 *
 * @author Fizza
 */
public class ProductsForm extends javax.swing.JFrame {

    /**
     * Creates new form Products
     */
    private ArrayList<Product> products;
    public ProductsForm() {
        initComponents();
        products = Product.fetchProducts();
        displayProducts();
        GetCat();
    }
    
    private void displayProducts() {
        String[] columnNames = {"ID", "Name", "Qty","Price", "Category"};
        String[][] data = new String[products.size()][];
        for (int i = 0; i < products.size(); i++) {
            Product product = products.get(i);
            data[i] = new String[] {
                String.valueOf(product.getId()),
                product.getName(), String.valueOf(product.getQuantity()),
                String.valueOf(product.getPrice()), product.getCategory()
            };
        }
        
        ProductTable.setModel(new DefaultTableModel(data, columnNames));
    }
    private void GetCat(){
        ArrayList<Category> cat = Category.fetchCat();
        for (Category cat1: cat) {
            catCb.addItem(cat1.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        prodName_field = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        prodId_field = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        prodQty_field = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        prodPrice_field = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        catCb = new javax.swing.JComboBox<>();
        add_btn = new javax.swing.JButton();
        edit_btn = new javax.swing.JButton();
        del_btn = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductTable = new javax.swing.JTable();
        productList = new javax.swing.JLabel();
        byName_btn = new javax.swing.JButton();
        refresh_btn = new javax.swing.JButton();
        close_label = new javax.swing.JLabel();
        employee_label = new javax.swing.JLabel();
        cat_label = new javax.swing.JLabel();
        logout_label = new javax.swing.JLabel();
        admin_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(249, 125, 42));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(249, 125, 42));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(249, 125, 42));
        jLabel3.setText("PROD ID");

        prodName_field.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        prodName_field.setForeground(new java.awt.Color(249, 125, 42));
        prodName_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodName_fieldActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(249, 125, 42));
        jLabel4.setText("MANAGE PRODUCTS");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(249, 125, 42));
        jLabel5.setText("NAME");

        prodId_field.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        prodId_field.setForeground(new java.awt.Color(249, 125, 42));
        prodId_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodId_fieldActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(249, 125, 42));
        jLabel6.setText("PRICE");

        prodQty_field.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        prodQty_field.setForeground(new java.awt.Color(249, 125, 42));
        prodQty_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodQty_fieldActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(249, 125, 42));
        jLabel7.setText("QUANTITY");

        prodPrice_field.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        prodPrice_field.setForeground(new java.awt.Color(249, 125, 42));
        prodPrice_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodPrice_fieldActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(249, 125, 42));
        jLabel8.setText("CATEGORY");

        catCb.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        catCb.setForeground(new java.awt.Color(249, 125, 42));
        catCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catCbActionPerformed(evt);
            }
        });

        add_btn.setBackground(new java.awt.Color(249, 125, 42));
        add_btn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        add_btn.setForeground(new java.awt.Color(255, 255, 255));
        add_btn.setText("Add");
        add_btn.setBorderPainted(false);
        add_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_btnMouseClicked(evt);
            }
        });
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        edit_btn.setBackground(new java.awt.Color(249, 125, 42));
        edit_btn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        edit_btn.setForeground(new java.awt.Color(255, 255, 255));
        edit_btn.setText("Edit");
        edit_btn.setBorderPainted(false);
        edit_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit_btnMouseClicked(evt);
            }
        });
        edit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_btnActionPerformed(evt);
            }
        });

        del_btn.setBackground(new java.awt.Color(249, 125, 42));
        del_btn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        del_btn.setForeground(new java.awt.Color(255, 255, 255));
        del_btn.setText("Delete");
        del_btn.setBorderPainted(false);
        del_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                del_btnMouseClicked(evt);
            }
        });
        del_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_btnActionPerformed(evt);
            }
        });

        clear_btn.setBackground(new java.awt.Color(249, 125, 42));
        clear_btn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        clear_btn.setForeground(new java.awt.Color(255, 255, 255));
        clear_btn.setText("Clear");
        clear_btn.setBorderPainted(false);
        clear_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clear_btnMouseClicked(evt);
            }
        });
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });

        ProductTable.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        ProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        ProductTable.setRowHeight(25);
        ProductTable.setSelectionBackground(new java.awt.Color(249, 125, 42));
        ProductTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        ProductTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ProductTable);

        productList.setBackground(new java.awt.Color(255, 255, 255));
        productList.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        productList.setForeground(new java.awt.Color(249, 125, 42));
        productList.setText("PRODUCTS LIST");

        byName_btn.setBackground(new java.awt.Color(249, 125, 42));
        byName_btn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        byName_btn.setForeground(new java.awt.Color(255, 255, 255));
        byName_btn.setText("Search By Name");
        byName_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                byName_btnMouseClicked(evt);
            }
        });

        refresh_btn.setBackground(new java.awt.Color(249, 125, 42));
        refresh_btn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        refresh_btn.setForeground(new java.awt.Color(255, 255, 255));
        refresh_btn.setText("Refresh");
        refresh_btn.setBorderPainted(false);
        refresh_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refresh_btnMouseClicked(evt);
            }
        });
        refresh_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(prodName_field, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(prodId_field)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(catCb, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(27, 27, 27)
                        .addComponent(prodQty_field, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(54, 54, 54)
                        .addComponent(prodPrice_field)))
                .addGap(80, 80, 80))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(edit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(del_btn)
                        .addGap(43, 43, 43)
                        .addComponent(clear_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(productList)
                        .addGap(34, 34, 34)
                        .addComponent(byName_btn)
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(116, 116, 116)
                                .addComponent(refresh_btn))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(refresh_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addComponent(prodId_field, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(prodName_field, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(catCb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prodQty_field, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(prodPrice_field, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(del_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productList)
                    .addComponent(byName_btn))
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        close_label.setBackground(new java.awt.Color(255, 255, 255));
        close_label.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        close_label.setForeground(new java.awt.Color(255, 255, 255));
        close_label.setText("X");
        close_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_labelMouseClicked(evt);
            }
        });

        employee_label.setBackground(new java.awt.Color(255, 255, 255));
        employee_label.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        employee_label.setForeground(new java.awt.Color(255, 255, 255));
        employee_label.setText("EMPLOYEE");
        employee_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employee_labelMouseClicked(evt);
            }
        });

        cat_label.setBackground(new java.awt.Color(255, 255, 255));
        cat_label.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        cat_label.setForeground(new java.awt.Color(255, 255, 255));
        cat_label.setText("CATEGORIES");
        cat_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cat_labelMouseClicked(evt);
            }
        });

        logout_label.setBackground(new java.awt.Color(255, 255, 255));
        logout_label.setFont(new java.awt.Font("Century Gothic", 2, 20)); // NOI18N
        logout_label.setForeground(new java.awt.Color(255, 255, 255));
        logout_label.setText("LOGOUT");
        logout_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_labelMouseClicked(evt);
            }
        });

        admin_label.setBackground(new java.awt.Color(255, 255, 255));
        admin_label.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        admin_label.setForeground(new java.awt.Color(255, 255, 255));
        admin_label.setText("ADMIN");
        admin_label.setToolTipText("");
        admin_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admin_labelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(close_label)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(logout_label)
                                        .addGap(30, 30, 30))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(cat_label)
                                        .addGap(18, 18, 18))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(employee_label)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(admin_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(close_label)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(employee_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cat_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(admin_label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logout_label)
                        .addGap(17, 17, 17))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void prodName_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodName_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodName_fieldActionPerformed

    private void prodId_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodId_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodId_fieldActionPerformed

    private void prodQty_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodQty_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodQty_fieldActionPerformed

    private void prodPrice_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodPrice_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodPrice_fieldActionPerformed

    private void catCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catCbActionPerformed

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_btnActionPerformed

    private void edit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_btnActionPerformed

    private void del_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_del_btnActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clear_btnActionPerformed

    private void add_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_btnMouseClicked
        if(prodId_field.getText().isEmpty()||prodName_field.getText().isEmpty()||prodPrice_field.getText().isEmpty()||prodQty_field.getText().isEmpty())
        {
         JOptionPane.showMessageDialog(this, "Missing Information!");   
        }
        else{
        try{
            Connection Con = Database.getInstance().getConnection();
            Statement St = Con.createStatement();
            PreparedStatement add = Con.prepareStatement("insert into PRODUCTTBL values(?,?,?,?,?)");
            add.setInt(1, Integer.parseInt(prodId_field.getText()));
            add.setString(2, prodName_field.getText());
            add.setString(3, prodQty_field.getText());
            add.setString(4, prodPrice_field.getText());
            add.setString(5, catCb.getSelectedItem().toString());
            add.executeUpdate();
            products = Product.fetchProducts();
            displayProducts();
        } catch(DerbySQLIntegrityConstraintViolationException e){
            JOptionPane.showMessageDialog(this, "ID ALREADY EXISTS!");
            prodId_field.setText("");
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Wrong Input");
        }
        catch (Exception e) {
            e.printStackTrace();
        }}
    }//GEN-LAST:event_add_btnMouseClicked

    private void clear_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clear_btnMouseClicked
        prodId_field.setText("");
        prodName_field.setText("");
        prodQty_field.setText("");
        prodPrice_field.setText("");
    }//GEN-LAST:event_clear_btnMouseClicked

    private void ProductTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductTableMouseClicked
        DefaultTableModel model = (DefaultTableModel)ProductTable.getModel();
        int Myindex = ProductTable.getSelectedRow();
        prodId_field.setText(model.getValueAt(Myindex, 0).toString());
        prodName_field.setText(model.getValueAt(Myindex, 1).toString());
        prodQty_field.setText(model.getValueAt(Myindex, 2).toString());
        prodPrice_field.setText(model.getValueAt(Myindex, 3).toString());
    }//GEN-LAST:event_ProductTableMouseClicked

    private void del_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_del_btnMouseClicked
        if(prodId_field.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "Enter The Product ID To Be Deleted");
        else{
            try{
               Connection Con = Database.getInstance().getConnection();
               String Query = "Delete from PRODUCTTBL where PRODID="+prodId_field.getText();
               Statement Add = Con.createStatement();
               Add.executeUpdate(Query);
               products = Product.fetchProducts();
               displayProducts();
               JOptionPane.showMessageDialog(this, "Product Deleted Successfully!");
            }
            catch(SQLSyntaxErrorException e){
             JOptionPane.showMessageDialog(this, "Wrong Input");
        }
            catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Wrong Input");
        }catch(Exception e){
                e.printStackTrace();
            }
        }     
    }//GEN-LAST:event_del_btnMouseClicked

    private void edit_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_btnMouseClicked
        if(prodId_field.getText().isEmpty()||prodName_field.getText().isEmpty()||prodQty_field.getText().isEmpty()||prodPrice_field.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "Missing Information!");
        else{
            try{
               Connection Con = Database.getInstance().getConnection();
               Statement St = Con.createStatement();
               String Query ="Update PRODUCTTBL set PRODNAME='" + prodName_field.getText()+"'"+",PRODQTY='"+prodQty_field.getText()+""+",PRODPRICE="+prodPrice_field.getText()+""+",PRODCAT="+catCb.getSelectedItem().toString()+""+"where PRODID="+prodId_field.getText();
               St.executeUpdate(Query);
               products = Product.fetchProducts();
               displayProducts();
               JOptionPane.showMessageDialog(this, "Product Updated!");
        }catch(SQLSyntaxErrorException e){
             JOptionPane.showMessageDialog(this, "Wrong Input");
        }
            catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Wrong Input");
        }catch (SQLException e) {
                e.printStackTrace();
            }
        }     
    }//GEN-LAST:event_edit_btnMouseClicked

    private void close_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_labelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_close_labelMouseClicked

    private void employee_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employee_labelMouseClicked
        new EmployeeForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_employee_labelMouseClicked

    private void cat_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cat_labelMouseClicked
        new CategoryForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cat_labelMouseClicked

    private void logout_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_labelMouseClicked
        new LoginForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logout_labelMouseClicked

    private void admin_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin_labelMouseClicked
        new UpdateAdminForm().setVisible(true);
    }//GEN-LAST:event_admin_labelMouseClicked

    private void byName_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_byName_btnMouseClicked
        String name = JOptionPane.showInputDialog("Enter Name Of The Product: ");
        products = Product.fetchByName(name);
        displayProducts();
    }//GEN-LAST:event_byName_btnMouseClicked

    private void refresh_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refresh_btnMouseClicked

        products = Product.fetchProducts();
        displayProducts();
    }//GEN-LAST:event_refresh_btnMouseClicked

    private void refresh_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refresh_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ProductTable;
    private javax.swing.JButton add_btn;
    private javax.swing.JLabel admin_label;
    private javax.swing.JButton byName_btn;
    private javax.swing.JComboBox<String> catCb;
    private javax.swing.JLabel cat_label;
    private javax.swing.JButton clear_btn;
    private javax.swing.JLabel close_label;
    private javax.swing.JButton del_btn;
    private javax.swing.JButton edit_btn;
    private javax.swing.JLabel employee_label;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logout_label;
    private javax.swing.JTextField prodId_field;
    private javax.swing.JTextField prodName_field;
    private javax.swing.JTextField prodPrice_field;
    private javax.swing.JTextField prodQty_field;
    private javax.swing.JLabel productList;
    private javax.swing.JButton refresh_btn;
    // End of variables declaration//GEN-END:variables
}
